development:
  secret_key_base: secret_key_base
  yahoo:
    yahoo_key: <%= ENV["YAHOO_ACCESS_KEY"] %>
    yahoo_secret: <%= ENV["YAHOO_SECRET_KEY"] %>
  aws:
    access_key_id: <%= ENV["AWS_ACCESS_KEY"] %>
    secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
    s3_bucket_name: <%= ENV["AWS_BUCKET"] %>
test:
  secret_key_base: secret_key_base
  yahoo:
    yahoo_key: <%= ENV["YAHOO_ACCESS_KEY"] %>
    yahoo_secret: <%= ENV["YAHOO_SECRET_KEY"] %>
  aws:
    access_key_id: <%= ENV["AWS_ACCESS_KEY"] %>
    secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
    s3_bucket_name: <%= ENV["AWS_BUCKET"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  yahoo:
    yahoo_key: <%= ENV["YAHOO_ACCESS_KEY"] %>
    yahoo_secret: <%= ENV["YAHOO_SECRET_KEY"] %>
  aws:
    access_key_id: <%= ENV["AWS_ACCESS_KEY"] %>
    secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
    s3_bucket_name: <%= ENV["AWS_BUCKET"] %>